# Use offivial Python Slim image
FROM python:3.11-Slim

# Set the working directory inside the container
WORKDIR /

# Copy only requirements first to leverage packages
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application inside the container
COPY . .

# Expose the FastAPI port
EXPOSE 8000

# Run the FastAPI application with Uvicorn
CMD ["uvicorn", "server:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]